---
deployment:
  tasks:
    - export DEPLOYPATH=/home/bintangwisatahol/public_html
    - /usr/bin/rsync -av --exclude '.git' --exclude '.cpanel.yml' --exclude '.htaccess' --exclude 'index.php' ./ $DEPLOYPATH/
